spring.application.name=ecom-proj
server.port=8090

spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis
spring.cache.redis.cache-null-values=true

spring.datasource.url=jdbc:h2:mem:bnk;INIT=CREATE SCHEMA IF NOT EXISTS PROJECTS;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.show-sql=true
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false


#spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
